### ISSUE TITLE
Cross-origin frame blocked https://speakerdeck.com

### ISSUE THREAD

**Issue by neiesc** [neiesc/neiesc.github.io#195]
Blocked a frame with origin "https://speakerdeck.com" from accessing a cross-origin frame.

![image](https://user-images.githubusercontent.com/251643/69904850-c03f2600-138a-11ea-9e10-b857bb601067.png)
```
player.js:74 Uncaught DOMException: Blocked a frame with origin "https://speakerdeck.com" from accessing a cross-origin frame.
    at e.value (https://speakerd.herokuapp.com/assets/player-c798dabe4938945bc885.js:1:4710)
    at new e (https://speakerd.herokuapp.com/assets/player-c798dabe4938945bc885.js:1:3565)
    at Function.c.init (https://speakerd.herokuapp.com/assets/player-c798dabe4938945bc885.js:1:12891)
    at HTMLDocument.<anonymous> (https://speakerd.herokuapp.com/assets/player-c798dabe4938945bc885.js:1:2400)
```

**Comment by neiesc** [comment]
Removed 3rd party in Palestras #214
